# Project: occupancy_grid
# Makefile created by Dev-C++ 5.4.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = PointWiseOclusionTest.o Laservoxel.o main.o Traj2LaserPoints.o $(RES)
LINKOBJ  = PointWiseOclusionTest.o Laservoxel.o main.o Traj2LaserPoints.o $(RES)
LIBS     = -L"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"D:/MappingLibrary/Mapping/Library/lib64" -lLaserScan -lPhotogrammetry -lBuildings -lEispack -lLinpack -lANN -lnewmat -lgfortran -g3 -llas 
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/MappingLibrary/Mapping/Library/Photogrammetry/include" -I"D:/MappingLibrary/Mapping/Library/LaserScan/include" -I"D:/MappingLibrary/Mapping/Library/Buildings/include" -I"D:/MappingLibrary/Mapping/Foreign/ANN/include/ANN"
CXXINCS  = -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/MappingLibrary/Mapping/Library/Photogrammetry/include" -I"D:/MappingLibrary/Mapping/Library/LaserScan/include" -I"D:/MappingLibrary/Mapping/Library/Buildings/include" -I"D:/MappingLibrary/Mapping/Foreign/ANN/include/ANN"
BIN      = occupancy_grid.exe
CXXFLAGS = $(CXXINCS)  -std=c++0x
CFLAGS   = $(INCS)  -std=c++0x
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

PointWiseOclusionTest.o: PointWiseOclusionTest.cpp
	$(CPP) -c PointWiseOclusionTest.cpp -o PointWiseOclusionTest.o $(CXXFLAGS)

Laservoxel.o: Laservoxel.cpp
	$(CPP) -c Laservoxel.cpp -o Laservoxel.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Traj2LaserPoints.o: Traj2LaserPoints.cpp
	$(CPP) -c Traj2LaserPoints.cpp -o Traj2LaserPoints.o $(CXXFLAGS)
